services:
  - type: web
    name: pinyin-app
    env: python
    plan: free
    buildCommand: cd myproject && python manage.py migrate
    startCommand: cd myproject && gunicorn myproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
    buildContext: .
    rootDir: .
