services:
  - type: web
    name: pinyin-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python myproject/manage.py migrate && python myproject/manage.py collectstatic --noinput
    startCommand: gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False
    autoDeploy: true
