services:
  - type: web
    name: pinyin-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python myproject/manage.py migrate
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
    buildContext: .
