services:
  - type: web
    name: pinyin-app
    env: python
    buildCommand: "cd myproject && pip install -r requirements.txt"
    startCommand: "cd myproject && python manage.py runserver 0.0.0.0:$PORT"
    plan: free